before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: server-updater
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    ldflags: >-
      -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X
      main.date={{.Date}}

archives:
  - 
    format: binary
    replacements:
      '386': 32-bit
checksum:
  name_template: checksums.txt
